export const arrInput = [
  {
    label: 'Your last name',
    caption: 'lastName',
    type: 'text',
    placeholder: 'For Example Doe',
    name: 'lastName',
    select: false,
    required: true,
    pattern: /^[A-Za-z]+$/,
    errorText: 'Enter your last name',
  } as const,
  {
    label: 'Your first name',
    caption: 'firstName',
    type: 'text',
    placeholder: 'For Example Jhon',
    name: 'firstName',
    select: false,
    required: true,
    pattern: /^[A-Za-z]+$/,
    errorText: 'Enter your first name',
  } as const,
  {
    label: 'Your patronymic',
    caption: 'middleName',
    type: 'text',
    placeholder: 'For Example Victorovich',
    name: 'middleName',
    select: false,
    pattern: /^[A-Za-z]+$/,
    required: false,
  } as const,
  {
    label: 'Select term',
    caption: 'term',
    name: 'term',
    select: true,
    required: true,
  } as const,
  {
    label: 'Your email',
    caption: 'email',
    type: 'email',
    placeholder: 'test@gmail.com',
    name: 'email',
    select: false,
    required: true,
    pattern: /[a-z\d!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z\d!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z\d](?:[a-z\d-]*[a-z\d])?\.)+[a-z\d](?:[a-z\d-]*[a-z\d])?/,
    errorText: 'Incorrect email address',
  } as const,
  {
    label: 'Your date of birth',
    caption: 'birthdate',
    type: 'date',
    placeholder: 'Select Date and Time',
    name: 'birthdate',
    select: false,
    required: true,
    min: '1900-01-01',
    max: '2005-08-01',
    maxLength: 10,
    errorText: 'Incorrect date of birth',
  } as const,
  {
    label: 'Your passport series',
    caption: 'passportSeries',
    type: 'number',
    placeholder: '0000',
    name: 'passportSeries',
    select: false,
    required: true,
    maxLength: 4,
    minLength: 4,
    pattern: /^(?! )(?!.* $)(?! )(\d*$)/,
    errorText: 'The series must be 4 digits',
  } as const,
  {
    label: 'Your passport number',
    caption: 'Passport number',
    type: 'number',
    placeholder: '000000',
    name: 'passportNumber',
    select: false,
    required: true,
    maxLength: 6,
    minLength: 6,
    pattern: /^(?! )(?!.* $)(?! )(\d*$)/,
    errorText: 'The series must be 6 digits',
  } as const,

];